/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateBlogPostRequest } from '../model/models';
import { CreateBlogPostResponse } from '../model/models';
import { GetAllBlogPostResponse } from '../model/models';
import { GetBlogPostByIdResponse } from '../model/models';
import { UpdateBlogPostRequest } from '../model/models';
import { UpdateBlogPostResponse } from '../model/models';
import { UpdateUser400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateBlogPostRequestParams {
    createBlogPostRequest: CreateBlogPostRequest;
}

export interface DeleteBlogPostRequestParams {
    id: number;
}

export interface GetBlogPostByIdRequestParams {
    id: number;
}

export interface UpdateBlogPostRequestParams {
    updateBlogPostRequest: UpdateBlogPostRequest;
}


export interface BlogPostControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createBlogPost(requestParameters: CreateBlogPostRequestParams, extraHttpRequestParams?: any): Observable<CreateBlogPostResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteBlogPost(requestParameters: DeleteBlogPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllBlogPosts(extraHttpRequestParams?: any): Observable<Array<GetAllBlogPostResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getBlogPostById(requestParameters: GetBlogPostByIdRequestParams, extraHttpRequestParams?: any): Observable<GetBlogPostByIdResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateBlogPost(requestParameters: UpdateBlogPostRequestParams, extraHttpRequestParams?: any): Observable<UpdateBlogPostResponse>;

}
