/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateCommentRequest } from '../model/models';
import { CreateCommentResponse } from '../model/models';
import { GetAllCommentResponse } from '../model/models';
import { GetCommentByIdResponse } from '../model/models';
import { UpdateCommentRequest } from '../model/models';
import { UpdateCommentResponse } from '../model/models';
import { UpdateUser400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateCommentRequestParams {
    createCommentRequest: CreateCommentRequest;
}

export interface DeleteCommentRequestParams {
    id: number;
}

export interface GetCommentByIdRequestParams {
    id: number;
}

export interface UpdateCommentRequestParams {
    updateCommentRequest: UpdateCommentRequest;
}


export interface CommentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createComment(requestParameters: CreateCommentRequestParams, extraHttpRequestParams?: any): Observable<CreateCommentResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteComment(requestParameters: DeleteCommentRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllComments(extraHttpRequestParams?: any): Observable<Array<GetAllCommentResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getCommentById(requestParameters: GetCommentByIdRequestParams, extraHttpRequestParams?: any): Observable<GetCommentByIdResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateComment(requestParameters: UpdateCommentRequestParams, extraHttpRequestParams?: any): Observable<UpdateCommentResponse>;

}
